SELECT 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B

LEFT JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID

LEFT JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID

WHERE 
    YEAR(SALES_DATE) = 2022 
    AND MONTH(SALES_DATE) = 1

GROUP BY 
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, 
    B.CATEGORY DESC



