-- 코드를 입력하세요
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FP.PRICE* FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
LEFT JOIN FOOD_ORDER AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE AMOUNT IS NOT NULL
AND YEAR(FO.PRODUCE_DATE) = 2022
AND MONTH(FO.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC