WITH RANK_DATA AS (
    SELECT 
        JULY.SHIPMENT_ID,
        JULY.FLAVOR,
        RANK() OVER (ORDER BY (FIRST_HALF.TOTAL_ORDER + SUM(JULY.TOTAL_ORDER)) DESC) AS RANK_TL
    FROM FIRST_HALF   
    RIGHT JOIN JULY 
    ON FIRST_HALF.SHIPMENT_ID = JULY.SHIPMENT_ID
    GROUP BY FLAVOR
)

SELECT
    FLAVOR
FROM RANK_DATA
WHERE RANK_TL <= 3
LIMIT 3
