-- 코드를 입력하세요
WITH BEST_PRICE AS (
    SELECT
        PRODUCT_ID,
        CATEGORY,
        PRICE,
        PRODUCT_NAME,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
    FROM FOOD_PRODUCT
)

SELECT 
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM BEST_PRICE    
WHERE RANKING = 1
GROUP BY CATEGORY
HAVING 
CATEGORY LIKE '%과자%'
OR CATEGORY LIKE '%국%'
OR CATEGORY LIKE '%김치%'
OR CATEGORY LIKE '%식용유%'
ORDER BY PRICE DESC
    
    